### ISSUE TITLE
How do you build this to the final deployable web page?

### ISSUE THREAD

**Issue by doggodanubus** [lax4mike/firefly#1]
I'd prefer building it if possible unless copying your web version is allowed.

**Comment by lax4mike** [comment]
Hi! You should be able to `npm install` then `gulp prod` to build.  It's been a long time since I worked on this but let me know if that works!

**Comment by doggodanubus** [comment]
Sadly it no longer works. There are a log of deprecated warnints then it fails at node-sass as they've removed something and are now at v6. I think it would need a rewrite but I merely wanted it as a web toy.

**Comment by lax4mike** [comment]
Hi @doggodanubus -  I've updated the build so it should work now if you pull the latest! Try `npm install` then `npm start`.  That should bring it up locally and allow you to change code live.  If you want to build for production, do `npm run build`, then copy the `/build/` directory to your host. Let me know if this works!

p.s. I'm curious what you're using this for!

**Comment by doggodanubus** [comment]
It builds with npm install and npm start which works at localhost.  npm build builds it and that works fine with a local websever.
Thank you for this.

I intend to use it as just an example webtoy while I learn how to setup a VPS with webserver and domain name. So many of the more interesting webtoys go away so I'd like to preserve the more interesting ones when allowed.
